### ISSUE TITLE
Alignment options

### ISSUE THREAD

**Issue by nicksherman** [LettError/longboardRoboFontExtension#6]
Love the new updated Longboard experience so far! Thanks for making it.

One thing that would make it even more useful is if there were settings to view the overlays with their left or right side bearings aligned (as alternatives to having the overlays centered on top of each other).

**Comment by LettError** [comment]
Thanks! Maybe. Alignment is complex. You mean preview left align on the left margin / preview right align on the right margin?

**Comment by nicksherman** [comment]
Yeah, so – for example – you could more easily see how the sidebearing distances change across the designspace.

**Comment by LettError** [comment]
Not unreasonable, I'll think about it.
